const ADD_TODO = 'ADD_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const UPDATE_USER = 'UPDATE_USER';
exports.ADD_TODO = 'ADD_TODO';
exports.TOGGLE_TODO = 'TOGGLE_TODO';
exports.UPDATE_USER = 'UPDATE_USER';